export default {
	control: 0,
	worker: 0,
	infra: 0,
	cores: 0,
	coretotal: 0,
	memory: 0,
	localtotal: 0,
	filetotal: 0,
	blocktotal: 0,
	objtotal: 0,
	totalnodes: 0,

	minRequireCoreControl: 4,
	minRequireCoreWorker: 2,
	minRequireCoreInfra: 0,
	minRequireMemControl: 16,
	minRequireMemWorker: 8,
	minRequireMemInfra: 0,
	minRequireDiskControl: 100,
	minRequireDiskWorker: 100,
	minRequireDiskInfra: 0,
	minRequireBootstrapCpu: 4,
	minRequireBootstrapMem: 16,
	minRequireBootstrapStorage: 100,
}
